/* globals define */
define({
  root: {
    signIn: 'Sign in',
    signUp: 'Sign up',
    username: 'Username',
    updateWidget: "An updated widget is available <a href=\"{update_url}\" target=\"_blank\">here</a>.",
    updateCriticalWidget: "A critical update to the  widget is required, <a href=\"{update_url}\" target=\"_blank\">click here</a> to update.",
    showCoverage: 'Mapillary Coverage Layer',
    callbackUrl: 'Callback URL (optional)',
    callbackUrlInstruction: 'Only necessary if your Mapillary widget is deployed to a different domain than the application. URL must point to "oauth-callback.html".',
    defaultOrganization: 'Default Organization (optional)',
    defaultUserName: "Default username filter (optional)",
    defaultUserNameInstruction: "Separate multiple usernames by comma, no spaces.",
    clientId: "Mapillary Client Token",
    clientSecret: "Mapillary Client Secret",
    obtainClientId: "Your Client Token is your access token. It can be generated in your account settings page.",
    clientIdInstruction: "Your Client Token can be generated in your account settings page at ",
    clientSecretInstruction: "Your client Secret can be generated in your account settings page at ",
    advancedOptions: "Advanced Options",
    layerColors: "Layer Colors",
    hideAuthentication: "Hide login and registration buttons",
    hideAuthenticationInstruction: "If checked, the user will not be able to login to their account nor have an option to register. This will also prevent access to advanced features.",
    hideUserFilter: "Hide username filter",
    hideUserFilterInstruction: "If checked, the user will not be able to modify the username filter. This will still retain any default username filter presets.",
    imageInstruction: "Checking this will present a toggle for image transitions.",
    imageDetails: "Show image transition toggle",
    directionInstruction: "Unchecking this will remove large arrows for spatial navigation being overlaid on images",
    directionDetails: "Allow spatial navigation",
    sequenceInstruction: "Unchecking this will remove small arrows at top of viewer for navigation within a sequence",
    sequenceDetails: "Allow sequence navigation",
    bearingInstruction: "Unchecking this will remove the indicator of the camera angle at bottom right of the viewer",
    bearingDetails: "Display camera angle indicator",
    clearCoverageDetails: "Clear coverage on widget close",
    clearCoverageInstruction: "Unchecking this will allow the Mapillary coverage layer and current filters to persist even when the widget is closed",
    useImageTransition: "Show image transitions",
    useImageTransitionInstruction: "Unchecking this will remove any motion blending between images when navigating.",
    enableProxyDetails: "Enable Esri Resource Proxy",
    enableProxyInstruction: "For use when deployed inside ArcGIS Portal. For more information, see ",
    proxyUrlDetails: "Esri Resource Proxy URL",
    proxyUrlInstruction: "Enter the url to your deployed proxy; e.g. 'https://yourserver.com/proxy/proxy.ashx'",
    enableAnonymous: "Enable Anonymous Access",
    enableAnonymousInstrictuon: "Users will not need to sign into the widget",
    organizationId: "Mapillary Orginization Key",
    organizationIdInstruction: "Enter the id for your Mappilary Orginization"

  },
  "ar": 0,
  "bs": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "hi": 0,
  "hr": 0,
  "it": 0,
  "id": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sr": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
